
// const cars = [
//     {
//         name: "911 Carrera GTS",
//         type: "Type 992",
//         price: 950,
//         capacity: 2,
//         transmission: "Manual",
//         mileage: 200,
//         img: "src/assets/images/car1.png",
//     },
//     {
//         name: "Porsche Taycan",
//         type: "2/4, 4s",
//         price: 950,
//         capacity: 4,
//         transmission: "Manual",
//         mileage: 200,
//         img: "src/assets/images/car2.png",
//     },
//     {
//         name: "Panamera 4.4s",
//         type: "E-Hybrid",
//         price: 950,
//         capacity: 4,
//         transmission: "Manual",
//         mileage: 200,
//         img: "src/assets/images/car5.png",
//     },
//     {
//         name: "Porsche 718",
//         type: "Spyder",
//         price: 950,
//         capacity: 2,
//         transmission: "Manual",
//         mileage: 200,
//         img: "src/assets/images/car1.png",
//     },
//     {
//         name: "Porsche Macan",
//         type: "Compact SUV",
//         price: 900,
//         capacity: 5,
//         transmission: "Automatic",
//         mileage: 250,
//         img: "src/assets/images/car6.png",
//     },
//     {
//         name: "Cayenne Coupe",
//         type: "Luxury SUV",
//         price: 1000,
//         capacity: 5,
//         transmission: "Automatic",
//         mileage: 200,
//         img: "src/assets/images/car1.png",
//     },
//     {
//         name: "Porsche Boxster",
//         type: "Convertible",
//         price: 850,
//         capacity: 2,
//         transmission: "Manual",
//         mileage: 150,
//         img: "src/assets/images/car2.png",
//     },
//     {
//         name: "Porsche 911 Turbo",
//         type: "Performance",
//         price: 1200,
//         capacity: 2,
//         transmission: "Automatic",
//         mileage: 200,
//         img: "src/assets/images/car5.png",
//     },
// ];

// export default cars;
